//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stranicaFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artifacts()
        {
            this.Museums = new HashSet<Museums>();
        }
    
        public int artifact_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public System.DateTime acquisition_date { get; set; }
        public string condition { get; set; }
        public decimal cost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Museums> Museums { private get; set; }
    }
}
