//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stranicaFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifacts
    {
        public int artifact_id { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> acquisition_date { get; set; }
        public string condition { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> museum_id { get; set; }
    
        public virtual Museums Museums { private get; set; }
    }
}
