//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artifacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artifacts()
        {
            this.Categories1 = new HashSet<Categories>();
        }
    
        public int ArtifactID { get; set; }
        public string ArtifactName { get; set; }
        public string ArtifactDescription { get; set; }
        public string Century { get; set; }
        public Nullable<int> MuseumID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Museums Museums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories1 { get; set; }
    }
}
